# if you want to try the docker as your development env:
##########################################################
# Run:
#   docker-compose run rust
version: "3.3"
services:
  rust:
    privileged: true
    build:
      context: .
    image: ghcr.io/ibm-xaas/dev-env:main
    volumes:
      # For future ssh use in development
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - .:/rust
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.gitconfig:/home/ubuntu/.gitconfig:ro
    working_dir: /rust

#  dev-env-workdir:
#    privileged: true
#    build:
#      context: .
#    image: ghcr.io/ibm-xaas/dev-env:latest
#    volumes:
#      # For future ssh use in development
#      - ~/.ssh:/home/ubuntu/.ssh:ro
#      - .:$WORKDIR
#    environment:
#      IBMCLOUD_API_KEY: "$IBMCLOUD_API_KEY"
#    working_dir: $WORKDIR
#
